// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK55vj8lkMQS8JMgRhPbViTvfqBVpZtuc',
    appId: '1:1055290116865:web:dcd88bad19d4663b1fe900',
    messagingSenderId: '1055290116865',
    projectId: 'agritech-a8b38',
    authDomain: 'agritech-a8b38.firebaseapp.com',
    storageBucket: 'agritech-a8b38.firebasestorage.app',
    measurementId: 'G-YQDC4RL97L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1oxBSi6wLsf-hwz0FFxfCAzOsQD-deMs',
    appId: '1:1055290116865:android:36c72274c844be3a1fe900',
    messagingSenderId: '1055290116865',
    projectId: 'agritech-a8b38',
    storageBucket: 'agritech-a8b38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS92nlw-6jGkqz23xsAeAxkpTAxsk3MOE',
    appId: '1:1055290116865:ios:9be8d213e6888cbc1fe900',
    messagingSenderId: '1055290116865',
    projectId: 'agritech-a8b38',
    storageBucket: 'agritech-a8b38.firebasestorage.app',
    iosBundleId: 'com.example.agritech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS92nlw-6jGkqz23xsAeAxkpTAxsk3MOE',
    appId: '1:1055290116865:ios:9be8d213e6888cbc1fe900',
    messagingSenderId: '1055290116865',
    projectId: 'agritech-a8b38',
    storageBucket: 'agritech-a8b38.firebasestorage.app',
    iosBundleId: 'com.example.agritech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK55vj8lkMQS8JMgRhPbViTvfqBVpZtuc',
    appId: '1:1055290116865:web:7c1af3326befeb171fe900',
    messagingSenderId: '1055290116865',
    projectId: 'agritech-a8b38',
    authDomain: 'agritech-a8b38.firebaseapp.com',
    storageBucket: 'agritech-a8b38.firebasestorage.app',
    measurementId: 'G-3DWSRBZTTW',
  );
}
